### ISSUE TITLE
Error message doesn't go away after successful login

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/signon#1471]
I tried logging into Signon, and accidentally put in the wrong 2FA code.

When I then entered the correct 2FA code, I signed in successfully, but the error message continued to show at the top of the page:

<img width="909" alt="Screenshot 2020-07-23 at 12 16 33" src="https://user-images.githubusercontent.com/5111927/88280779-5fc87480-ccde-11ea-9980-fddd0ddfc9c8.png">

I would expect the error message to disappear.

**Comment by floehopper** [comment]
I just tried this in integration and it still seems to be a problem. While it doesn't cause any actual problems per se, it's potentially very confusing to the user!

**Comment by floehopper** [comment]
Now tracking this in https://trello.com/c/9C8iNaKn

**Comment by floehopper** [comment]
Fixed in #2185
