### ISSUE TITLE
Passphrase could do with contextual help

### ISSUE THREAD

**Issue by jabley** [alphagov/signon#330]
I was in a user research session and the participant wasn't sure what that meant.

This was part of completing sign-up. The copy in (or just link to) [the service manual should be fine](https://www.gov.uk/service-manual/making-software/logins#credentials).

**Comment by fofr** [comment]
@jabley If you could share the research session clip with Core team, that would be really useful

**Comment by jabley** [comment]
@fofr wasn't in the lab, so no clip available unfortunately.

**Comment by tijmenb** [comment]
"Passphrase" was renamed to "password", so this should now be fixed.
