### ISSUE TITLE
Consider changing the password rotation requirement

### ISSUE THREAD

**Issue by matthewford** [alphagov/signon#524]
The ncsc website is down so I cannot link to the guideance 🙁 , but from their twitter https://twitter.com/ncsc/status/808258353554132992

https://www.ncsc.gov.uk/articles/problems-forcing-regular-password-expiry (for when the website is back live).

**Comment by fofr** [comment]
A good quote from the article:

> It’s one of those counter-intuitive security scenarios; the more often users are forced to change passwords, the greater the overall vulnerability to attack. What appeared to be a perfectly sensible, long-established piece of advice doesn’t, it turns out, stand up to a rigorous, whole-system analysis.

**Comment by fofr** [comment]
We also don't do the following very well, meaning regular password resets are more burdensome:
> Allow users to reset password easily, quickly and cheaply.


We uncovered these problems during 2-step verification research but didn't fix them.

**Comment by matthewford** [comment]
Having reset my passphrase again - I'm reminded of this old issue, please consider it.

**Comment by boffbowsh** [comment]
This is on our backlog of work for Signon, but we don't currently have any work on it planned in our [Roadmap](https://app.productplan.com/p/bUmH4fHC0hOivX-E2LYMu2hg9uEhkWp_)

**Comment by matthewford** [comment]
Hey @boffbowsh, need any help with this one? 

I could see if we can carve out some time from Tariff as we use our own signon instance on dev.

**Comment by boffbowsh** [comment]
Pull Requests are very welcome :)
