### ISSUE TITLE
Rename signonotron2 as "sign-on"

### ISSUE THREAD

**Issue by fofr** [alphagov/signon#525]
signonotron2 is referred to as "Sign on"

**Comment by tijmenb** [comment]
I think this should read "Signon"? I've not seen "Sign on" / "sign-on" used.

**Comment by fofr** [comment]
Signon isn't a word.

**Comment by alexmuller** [comment]
We deploy it as an app as "signon" and refer to it in interface as "GOV.UK Signon". I'd be in favour of renaming this repo to "signon" to start with because that will remove quite a lot of confusion and complexity.

**Comment by alexmuller** [comment]
@boffbowsh has got rid of the tron bit, feel free to reopen if you feel strongly about the hyphen or space.
