### ISSUE TITLE
2 step verification failure should tell the user to check their phone time

### ISSUE THREAD

**Issue by alexmuller** [alphagov/signon#534]
TOTP is based on the time of the device that the TOTP is calculated on. When a user fails 2SV, we should ask them to check the time of their phone or whatever they're using.

**Comment by fofr** [comment]
We had a plan for this, which was to show further advice on the second failed attempt (ie discounting a typo).

It was never implemented because Core stopped working on 2SV.

**Comment by floehopper** [comment]
From Joseph:

> It's already part of 2nd Line's macros and most users now have [2SV] Enabled, so I think it's redundant at this point

Closing
