### ISSUE TITLE
Weird issue with IE (perhaps when the session expires)

### ISSUE THREAD

**Issue by matthewford** [alphagov/signon#538]
Hello,

I had an issue with one of the HMRC editors who use the trade tariff not being able to login, I think it was perhaps a session expiration issue, or a permissions issue, but when they tried to click on to access the application (logged into signon, clicking on the app name), IE just tried to download a json file?

![image002](https://cloud.githubusercontent.com/assets/215/22797654/fb687e4a-eef6-11e6-9b85-65eb1df8d95d.png)

**Comment by tijmenb** [comment]
We haven't seen this behaviour since the original report, so closing for now. Please feel free to reopen if it surfaces again.
