### ISSUE TITLE
Suspension email should be sent with a reply-to address that works 

### ISSUE THREAD

**Issue by matthewford** [alphagov/signon#890]
Hello,

I only need my production login to check issues in production (which thankfully is once in a blue moon). Subsequently, I get suspended frequently, Gmail filters my emails into a pile where I miss the suspension warnings. I also cannot raise a support request that app is also behind SSO.

It would be great if you could reply to the suspension email to open a support request.

Thanks,
Matt 

PS. Can someone raise a support request to unsuspend matt@bitzesty.com

**Comment by cbaines** [comment]
Hey Matt, this sounds like a good suggestion.

> I only need my production login to check issues in production (which thankfully is once in a blue moon). Subsequently, I get suspended frequently, Gmail filters my emails into a pile where I miss the suspension warnings. I also cannot raise a support request that app is also behind SSO.

I'm not quite sure how Zendesk is setup, but you might be able to create a ticket here [1], which might eventually get to the right place.

1: https://www.gov.uk/contact/govuk

> PS. Can someone raise a support request to unsuspend [matt@bitzesty.com](mailto:matt@bitzesty.com)

I've done this now, apologies for the issue.
